//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "test_cases")]
pub struct Model {
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub problem_id: i32,
    pub hidden: bool,
    pub inputs: Json,
    #[sea_orm(column_type = "Text", nullable)]
    pub answer: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::problems::Entity",
        from = "Column::ProblemId",
        to = "super::problems::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Problems,
}

impl Related<super::problems::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Problems.def()
    }
}
